services:
  db:
    image: pgvector/pgvector:pg17
    container_name: math_rag_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/01_init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./database/02_db_schema.sql:/docker-entrypoint-initdb.d/02_db_schema.sql
      - ./database/03_pgvector_test.sql:/docker-entrypoint-initdb.d/03_pgvector_test.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: